### ISSUE TITLE
Issue Loading CSS via Angular CLI

### ISSUE THREAD

**Issue by Tahler** [travelist/angular2-fontawesome#11]
I'm building an application in Angular 2 and using your library to place font-awesome icons.

The Fa directives and components are compiling correctly, but the icon will only show up if I include font-awesome's css globally (in index.html). Including it in the component's styleUrls is seemingly impossible because of relative pathing. The iframe's css cannot find the webfonts from font-awesome.

I have tried using both 'vendor/font-awesome/css/font-awesome.css', '/vendor/font-awesome/css/font-awesome.css'.

I have verified that the CLI is properly building the vendor folder. Everything is there.

I am on RC 4 using Angular CLI.

**Comment by jmnuxeo** [comment]
Hi,
I have the same problem any idea ?

**Comment by travelist** [comment]
Thank you for the comments.

I've created demo branch: https://github.com/travelist/angular2-fontawesome/tree/demo/demo
`FaDirective` might work on this demo, but I'm straggling with `FaComponent` actually....

Sorry for this problem and will fix and update at some point of time (maybe after angular2 updates)
If there are any clue, plz let me know. it is really helpful.
