### ISSUE TITLE
Cannot find module 'angular2-fontawesome/components' --- compile time error

### ISSUE THREAD

**Issue by PrayagGanoje** [travelist/angular2-fontawesome#12]
I have followed all the steps given in the [readme file.](https://www.npmjs.com/package/angular2-fontawesome) ThenI am getting following error compile time.
[](https://www.npmjs.com/package/angular2-fontawesome)

**"Cannot find module 'angular2-fontawesome/components'"**

I am trying to use font-awesome with Angular 2 rc3 (application made with **angular CLI)**
can you please suggest how I can resolve this issue ??

**Comment by travelist** [comment]
@PrayagGanoje Thank you for the comment. And sorry for late replying, i had something to do these days.. 

If we use **angular-cli**, configuration might be something like following.

``` javascript
// angular-cli-build.js
// Note: This is only needed when we use angular-cli

var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      ...
      // Add following lines (1/2)
      'angular2-fontawesome/*.+(js|js.map)',
      'angular2-fontawesome/**/*.+(js|js.map)',
      'angular2-fontawesome/**/**/*.+(js|js.map)',

      // You need to add following lines as well (2/2)
      'font-awesome/css/*.*',
      'font-awesome/fonts/*.*'
    ]
```

``` javascript
// src/system-config.ts
// Note: This is only needed when we use angular-cli

const map: any = {
  // Add this line (1/2)
  'angular2-fontawesome': 'vendor/angular2-fontawesome'
};

/** User packages configuration. */
const packages: any = {
  // Add these lines (2/2)
  'angular2-fontawesome':{
    defaultExtension: 'js'
  }
};
```

Current [**README**](https://github.com/travelist/angular2-fontawesome/blob/master/README.md) might help for more info. I will close this issue, but if we hit the same error or there are something, plz feel free to open issues.

Thanks:)

**Comment by PrayagGanoje** [comment]
Thank you for your reply. 

I was missing **npm install** after all these setting. This command resolved my issue.
