### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by dekonunes** [travelist/angular2-fontawesome#15]
I'd like to change size of fa fa-line-chart, but when using a custom CSS, but font-size dont work.

Codes:
HTML:
`<a fa [name]="'line-chart'"></a>`

CSS:
`a {
    cursor: pointer;
    font-size: 60px;
}`

The pointer its working, font-size not. 
And how i can use  `fa-lg`, `fa-2x`, etc?

**Comment by travelist** [comment]
@dekonunes Thank you for opening this issue and sorry for late replying!

for using `fa-lg` or `fa-2x`, the following example might work.

``` html
<i fa [name]="'line-chart'" [size]="2" ></i>
<!-- valid size values are from 1 to 5 -->
```

in terms of setting `font-size` using CSS file, i will investigate later next week
