### ISSUE TITLE
Peer Invalid error when installing with Anuglar2 RC5

### ISSUE THREAD

**Issue by rashmidixit** [travelist/angular2-fontawesome#16]
This package needs to be updated to work with the latest RC5 build of Angular2. Right now when I try to install it, I geta PEERINVALID error because fontawesome needs common rc4 whereas all others use common rc5.

**Comment by travelist** [comment]
@rashmidixit Thank you for letting me know!
I gonna update the angular version next week (sorry I have less time for 1-2 days...)

**Comment by benh57** [comment]
Angular2 release is out now. Can this be updated to use 2.0.0?

**Comment by travelist** [comment]
@benh57 Thank you for the comment and sorry I could not make spare time recently.
I gonna quick check it this weekend.

Thanks

**Comment by guzmo** [comment]
Any progress? Updated to angular 2.0 now and the only thing not working seems to be angular2-fontawesome. I tried adding it in my Declarations but it gives this error.
`Uncaught Error: Unexpected value 'FaDirective' declared by the module 'MyAppModule'`

**Comment by travelist** [comment]
@guzmo Thank you for the comment and sorry for late updating on this repository. I updated this repository to deal with angular2.0.0 release. I gonna close this issue, but please feel free to open new issues or further queries. Thanks,

**Comment by guzmo** [comment]
@travelist Thanks :) Ill try it now

**Comment by guzmo** [comment]
I get (1,15): error TS2307: Cannot find module './lib/directives/fa.directive'.
and yes ./lib doesnt exist but ./src does

**Comment by guzmo** [comment]
It seems im not getting the latest code when im downloading 0.7.0?

**Comment by guzmo** [comment]
Sorry, seems I messed up and was pointing to a d.ts file
