### ISSUE TITLE
404 GET /node_modules/angular2-fontawesome/lib/

### ISSUE THREAD

**Issue by Vrael** [travelist/angular2-fontawesome#2]
I have updated to v0.1.2 with angular 2.0.0-beta.13 but I get a 404 error: 
`[1] 16.04.07 12:13:32 404 GET /node_modules/angular2-fontawesome/lib/`

My System.js configuration:

``` javascript
   <script>
        System.config({
            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                },
                "angular2-fontawesome": { defaultExtension: 'js'},
                "angular2-jwt": { defaultExtension: 'js' }
            },
            map: {
                'angular2-fontawesome': 'node_modules/angular2-fontawesome/lib',
                'angular2-jwt': 'node_modules/angular2-jwt/angular2-jwt.js',
                'moment': 'node_modules/moment/moment.js'
            }
        });
        System.import('app/main')
            .then(null, console.error.bind(console));
    </script>

```

In addition I tried it with:

``` javascript
 map: {
     'angular2-fontawesome': 'node_modules/angular2-fontawesome/lib/components.js',
 } 
```

but I get a similar message:

``` shell
[1] 16.04.07 12:20:03 404 GET /node_modules/angular2-fontawesome/lib/components/fa.component
[1] 16.04.07 12:20:03 404 GET /node_modules/angular2-fontawesome/lib/components/fa-stack.component
```

**Comment by travelist** [comment]
@Vrael Thank you for reporting the issue!

Would you mind to try the following configuration?:

``` javascript
 "angular2-fontawesome": { defaultExtension: 'js'},
```

``` javascript
 map: {
     'angular2-fontawesome': 'node_modules/angular2-fontawesome/lib/',
 } 
```

``` javascript
import {FaComponent} from 'angular2-fontawesome/components'
```

This **may be** fix the import issue, if it still cause errors, let me know the error messages.

**Comment by Vrael** [comment]
@travelist Thank you for your fast response!
The error still persists, I applied the configuration but now it doesn't find the module 'angular2-fontawesome/components': 
`[0] app/app.ts(9,29): error TS2307: Cannot find module 'angular2-fontawesome/components'.`

**Comment by travelist** [comment]
@Vrael Sorry for late replying, I couldn't have time these 3 days.

Instead of writing `import {FaComponent} from 'angular2-fontawesome/components';` in `app/app.ts`, do we try to write this line in `app/app.component.ts` file (I'm assuming Angular2 Quickstart Tutorial: https://angular.io/docs/ts/latest/quickstart.html).

May be this can fix this error. (but not 100% sure)

**Comment by Vrael** [comment]
I renamed app.ts to app.component.ts and I ensured the import is correctly but the message still persists: 

``` shell
app/app.component.ts(9,29): error TS2307: Cannot find module 'angular2-fontawesome/components'.
[1] 16.04.12 12:06:42 404 GET /node_modules/angular2-fontawesome/lib/
`
```

**Comment by Vrael** [comment]
It works changing the System.js:

``` javascript
      System.config({
            packages: {
                'app': {
                    format: 'register',
                    defaultExtension: 'js'
                },
                'node_modules/angular2-fontawesome': {
                    defaultExtension: 'js'
                },
            },
            paths: {
                'angular2-fontawesome': 'node_modules/angular2-fontawesome/lib/components',
            }
        });
        System.import('app/main')
            .then(null, console.error.bind(console));
```

So with the new System.js the import is as follow:

``` typescript
import { FaComponent } from 'angular2-fontawesome'
```

I'm not sure why with `map` is not enough and you must use `path` but this seems work again! Thx!

**Comment by ZoolWay** [comment]
Hello,

I am having similar issues with Angular 2 RC1. I have followed the Angular 2 quickstart guide, then the readme instructions here.

Added to SystemJS map:
`'angular2-fontawesome':       'node_modules/angular2-fontawesome/lib',`

Added to SystemJS packages:
`'angular2-fontawesome':       { defaultExtension: 'js' },`

Import:
`import { FaComponent } from 'angular2-fontawesome/components';`

Everything okay until here but of course nothing happens.
Then setting directives (without using in template):
`directives: [FaComponent]`

Browser console shows:
`
zone.js:101 GET http://localhost:3000/angular2/core 404 (Not Found)
rror: Error: XHR error (404 Not Found) loading http://localhost:3000/angular2/core
        at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:769:30)
        at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:356:38)
        at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:256:48)
        at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:423:34)
    Error loading http://localhost:3000/angular2/core as "angular2/core" from http://localhost:3000/node_modules/angular2-fontawesome/lib/components/fa.component.js
`

I tried some of the other variants from this issue thread too but without success.
VS code TypeScript and the command line marks the import statement red and says _cannot find module angular2-fontawesome/components_.
Without the trailing _components_ this does not happen.

**Comment by travelist** [comment]
@ZoolWay Thank you for the comment, and sorry for late replying.
I've just updated this package and README to support for Angular2 RC, so that this issue might be fixed. I'll close this issue, but please feel free to re-open or create new issues if I missed something. And thank you again for your comment:D

**Comment by bennyp123** [comment]
I've got this same issue with angular-cli and RC2:
    const map: any = {
      'angular2-fontawesome': 'node_modules/angular2-fontawesome',
    };

    /** User packages configuration. */
    const packages: any = {
      'angular2-fontawesome': {
        defaultExtension: 'js',
        format: 'esm'
      },
    };
and in angular-cli-build.js:

    module.exports = function(defaults) {
      return new Angular2App(defaults, {
        vendorNpmFiles: [
          ...
          'angular2-fontawesome/**/*.+(js|js.map)'
        ]
      });
    };

I think that system-config.ts should actually be pointing to vendor/angular2-fontawesome etc etc., 
the line mentioned above in angular-cli-build.js is meant to have the 3rd party lib files copied to dist/ but they're not copying for some reason.

**Comment by DVanderstoken** [comment]
Hello,

I'm having @ZoolWay same issue with angular 2.0.0-rc.3 :

In package.json, dependencies section :
`"angular2-fontawesome": "^0.5.0"`

In angular-cli-build.js :
`vendorNpmFiles: [
     (...)
      'angular2-fontawesome/*.+(js|js.map)',
      'angular2-fontawesome/**/*.+(js|js.map)',
      'angular2-fontawesome/**/**/*.+(js|js.map)',
      'font-awesome/css/*.*',
      'font-awesome/fonts/*.*',
      'angular2-fontawesome/*.+(js|js.map)',
      'angular2-fontawesome/**/*.+(js|js.map)',
      'angular2-fontawesome/**/**/*.+(js|js.map)',
      'font-awesome/css/*.*',
      'font-awesome/fonts/*.*'
]`

In system-config.ts :
`/*\* Map relative paths to URLs. */
const map: any = {
  'angular2-fontawesome':       'node_modules/angular2-fontawesome'
};

/*\* User packages configuration. */
const packages: any = {
  'angular2-fontawesome':       { defaultExtension: 'js' }
};`

Import in my component : 
`import { FaComponent } from 'angular2-fontawesome/components';`

And when I add the directive :
`directives: [FaComponent],`

Browser console shows :
`GET http://localhost:4200/node_modules/angular2-fontawesome/components.js 404 (Not Found)
Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/node_modules/angular2-fontawesome/components.js
        at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:4200/vendor/zone.js/dist/zone.js:769:30)
        at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
        at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
        at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:423:34)
    Error loading http://localhost:4200/node_modules/angular2-fontawesome/components.js as "angular2-fontawesome/components" from http://localhost:4200/app/components/menu/menu.component.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: XHR error (404 Not Found) loading http://localhost:4200/node_modules/angular2-fontawesome/components.js(…)
Error: Uncaught (in promise): Error: Error: XHR error (404 Not Found) loading http://localhost:4200/node_modules/angular2-fontawesome/components.js(…)
`

**Comment by travelist** [comment]
@DVanderstoken Thank you for the comment. Would you like to try

``` ts
const map: any = {
  'angular2-fontawesome': 'vendor/angular2-fontawesome'
};
```

instead of

``` ts
const map: any = {
  'angular2-fontawesome': 'node_modules/angular2-fontawesome'
};

```

`system-config.ts`

and restart the process.

The error seems we cannot access these URLs: `http://localhost:4200/node_modules/angular2-fontawesome/components.js`. This might be because `angular-cli` puts `node_module/*` files under `vendor` directory.

Reference: https://github.com/angular/angular-cli/wiki/3rd-party-libs#3-configure-systemjs-mappings-to-know-where-to-look-for-momentjs

**Comment by DVanderstoken** [comment]
Thanks for the soltuion !

**Comment by parid0kht** [comment]
I have the same problem and did this in below: add exactly the following line to your 

> systemjs.config.js

 file (Angular Quick Start Approach) 
`'angular2-fontawesome':      'node_modules/angular2-fontawesome/bundles/angular2-fontawesome.umd.js',`
