### ISSUE TITLE
Please update the Readme for the angular-cli instructions

### ISSUE THREAD

**Issue by jecourtney** [travelist/angular2-fontawesome#20]
If our application is built with angular-cli, the configuration is done with the following:

Install into project folder with:
npm install font-awesome --save

Modify the angular-cli.json file and in the **styles** section add:
`"../node_modules/font-awesome/css/font-awesome.css"`

Continue to modify the angular-cli.json file in the **addons** section add:
`"../node_modules/font-awesome/fonts/*.+(otf|eot|svg|ttf|woff|woff2)"`

Use fontawsome in html, like in app.component.html:
`<i class="fa fa-american-sign-language-interpreting fa-5x" aria-hidden="true"> </i>` 

ng build
ng serve

**Comment by travelist** [comment]
@jecourtney Thanks for the comment. I've attended some conference in a last week and have something to do this weekend. So will update next week hopefully. Thank you for mentioning this!
