### ISSUE TITLE
Unexpected value 'Angular2FontawesomeModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by BigRomanov** [travelist/angular2-fontawesome#21]
I am trying to use angular2-fontawesome 0.7.0 with Angular2 2.1.2 (Webpack 2.0)

After adding the import as it says in the manual I get:

Unexpected value 'Angular2FontawesomeModule' imported by the module 'AppModule'

I seems that 'lib' folder is missing from npm install

Any idea what I can do about it. Nothing seems to work

**Comment by travelist** [comment]
@BigRomanov Thanks for the comment. I tried by my self and got the same error

``` txt
Unexpected value 'Angular2FontawesomeModule' imported by the module 'AppModule'
```

``` typescript
// app/app.module.ts
import { Angular2FontawesomeModule } from 'angular2-fontawesome/angular2-fontawesome'
@NgModule({
  imports: [ BrowserModule, Angular2FontawesomeModule ], // Error comes from here....
  declarations: [ AppComponent ],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
```

I'm investigating on this issue, but please let me know if you find any clues.
Thanks.

**Comment by demetrio812** [comment]
Hello, same problem for me, did you find a solution?

Thanks

**Comment by thaismartins** [comment]
I got the same issue. Any solution? Thanks!

**Comment by travelist** [comment]
@BigRomanov @demetrio812 @thaismartinsprojects Thank you for the comments.
I updated this library to version *0.8.0* which might work without this error.
I gonna close this issue, but please feel free to open issues. Thanks!:)
