### ISSUE TITLE
 i cant find angular-cli-build.js in my angular-cli project folder structure 

### ISSUE THREAD

**Issue by prakashs-mtsin** [travelist/angular2-fontawesome#22]
to update the following line as per the angular2-fontawesome documentation.

// angular-cli-build.js 
// Note: This is not really tested!!! any comments are helpful 
// Note: This is only needed when we use angular-cli 
 
var Angular2App = require('angular-cli/lib/broccoli/angular2-app');
 
module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      ...
      // Add following lines (1/2) 
      'angular2-fontawesome/*.+(js|js.map)',
      'angular2-fontawesome/**/*.+(js|js.map)',
      'angular2-fontawesome/**/**/*.+(js|js.map)',
 
      // You need to add following lines as well (2/2) 
      'font-awesome/css/*.*',
      'font-awesome/fonts/*.*'
    ]

**Comment by travelist** [comment]
@prakashs-mtsin Thank you for the comment. I edited the README.md. Please let me know if you aware of anythings. Thanks!:)
