### ISSUE TITLE
Instructions not clear for installing module on Angular 2 quickstart (systemjs)

### ISSUE THREAD

**Issue by ntsokos** [travelist/angular2-fontawesome#27]
I am trying to follow the [readme](https://github.com/travelist/angular2-fontawesome/blob/master/README.md) using the latest quickstart version of angular 2 but cannot get things to work

Angular2 QuickStart > package.json and systemjs.config.js instructions are clear and seem to work fine
Usage > app.module.ts instructions are clear and seem to work fine 

Usage > sample template instructions do not seem to work 

1.  Syntax on the following seems wrong as there is a closing </i> tag at the end of the first line 

```
let sampleTemplate = `
<fa [name]="rocket" [border]=true></i>
<i fa [name]="rocket" [border]=true></i>
`
```
2.  How do the css and font directories get copied to the output? I can see instructions for angular-cli but nothing relevant to system.js (is there an extra step that needs to be done?) 

3.  I do not get what the "We can also use FaDirective if we want." means as there is no example on how to import or use a FaDirective.

4. By using the following sampleTemplate 

```
let sampleTemplate = `
<fa [name]="rocket" [border]=true></fa>
<i fa [name]="rocket" [border]=true></i>
`
```

I get the following outcome 

```
<fa ng-reflect-border="true">
  <i ng-reflect-ng-class="fa,fa-undefined,fa-border" class="fa fa-undefined fa-border"></i>
</fa>
<i fa="" class="fa fa-undefined fa-border" ng-reflect-border="true"></i>
```

Cheers 
Nikos

**Comment by craig-o-curtis** [comment]
Same issue. Did Quickstart from Angular.io. Followed instructions. No errors. No icons.

**Comment by amirtoole** [comment]
There's a missing step. You need to explicitly reference the css in your html file. You can use the following CDN if you wish:
```
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
```
