### ISSUE TITLE
Installation instructions to Angular CLI are deprecated 

### ISSUE THREAD

**Issue by QuentinBrosse** [travelist/angular2-fontawesome#35]
In this pull, the `addons` property has been deleted form the `angular-cli.json`: https://github.com/angular/angular-cli/pull/4052.

So, the:
> 2. `../node_modules/font-awesome/fonts/*.+(otf|eot|svg|ttf|woff|woff2)` to addons block of angular-cli.json.

must be modified.

Thanks ! :)

**Comment by nawwa** [comment]
Yo, so how should we install it ? Can't make it work..

**Comment by QuentinBrosse** [comment]
@nawwa 

1. Install packages: `npm i --save font-awesome angular2-fontawesome`.
2. Add `Angular2FontawesomeModule` in the `imports` of your `@NgModule`.
3. In your `.angular-cli.json`, add `"node_modules/font-awesome/css/font-awesome.min.css" in `styles`;
3. Use the package in your templates like this: `<fa [name]="'plus'"></fa>`.

:)

**Comment by xGeiben** [comment]
I find it hard to believe that this instruction i'ts not in the README docs:
Install packages: npm i --save font-awesome angular2-fontawesome.
