### ISSUE TITLE
Support Angular2 RC

### ISSUE THREAD

**Issue by soichih** [travelist/angular2-fontawesome#4]
Any chance of supporting angular2 RC?

**Comment by travelist** [comment]
@soichih Sorry for late replying, yes we will.
I've just aware of the pull requests related to this issues, so that will check soon. Thanks.

**Comment by travelist** [comment]
@soichih I updated this package, and support for Angular RC. It might solve this issue. Thank you for reporting, and please feel free to re-open this issue or create new one if we have something to improve/fix this package. Thank you.
