### ISSUE TITLE
Angular 5 update

### ISSUE THREAD

**Issue by gczuczy** [travelist/angular2-fontawesome#43]
Hello,

Could you please check whether this project requires an update for angular5? When I've tried to update a project to angular5, I got a warning for it:

```
npm WARN angular2-fontawesome@0.9.3 requires a peer of @angular/common@^4.0.0 but none was installed.
npm WARN angular2-fontawesome@0.9.3 requires a peer of @angular/core@^4.0.0 but none was installed.

```

Thanks

**Comment by travelist** [comment]
Hello, thanks for informing me of this issue. I gonna check and would like to fix it next week, thanks.

**Comment by mpgirro** [comment]
Hi, 

I can into the same issue. Would appreciate a fix! 

Thanks

**Comment by DawidvanGraan** [comment]
@travelist Any feedback on upgrading to Angular 5? Thank you!

**Comment by travelist** [comment]
Now `angular2-fontawesome (5.2.1)` is available. 
Sorry for taking time for this small change... I tried with my local environment, which seems it works.

I will close this issue, but feel free to re-open or comment further! Thanks, guys!
