### ISSUE TITLE
Font-awesome 5 Support ?

### ISSUE THREAD

**Issue by dsuwirya** [travelist/angular2-fontawesome#45]
Hi,

Any plan to support fontawesome v5 ?

https://github.com/FortAwesome/Font-Awesome

Thanks.

**Comment by travelist** [comment]
good point. Let me check how to do that over the weekend and hopefully makes some updates.
Thanks,

**Comment by travelist** [comment]
I figured out that there is a library supporting fontawesome5: 

https://github.com/FortAwesome/angular-fontawesome

Meanwhile, this `angular2-fontawesome` may not support for fontawesome5 to avoid to invent the wheel again. FA5 changed the way to specify icons and behaviors, so it is plenty of time taking changes to support their features at the same time having compatibility with FA4.

Let me know if there are any demands for this library to support FA5.

Thx
