### ISSUE TITLE
Ivy compiler support? (angular 9 migration)

### ISSUE THREAD

**Issue by slavafomin** [travelist/angular2-fontawesome#48]
Hello!

Thank you for this great library!

However, I'm getting the following error when trying to migrate from angular 8 to 9 (which uses new Ivy compiler):

```
ERROR in node_modules/angular2-fontawesome/src/index.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (angular2-fontawesome/angular2-fontawesome) which declares Angular2FontawesomeModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

1 export declare class Angular2FontawesomeModule {
```

Thanks!

**Comment by travelist** [comment]
Hi, thank you for having an interest in this library. This library hasn't been maintained a long time and there is a better alternative to do the same job by the font-awesome team (with active development): https://github.com/FortAwesome/angular-fontawesome

I would like you to consider using their library during your migration.. but please let me know if you really need to use this library; I'm happy to investigate this compatibility issue.

Thanks!

**Comment by ambujkhanna** [comment]
Is this library compatible with Angular 9+ version now?

**Comment by travelist** [comment]
No, this is library is no longer maintained and hasn't been tested with recent Angular releases. I'd like to ask you to consider using https://github.com/FortAwesome/angular-fontawesome!
