### ISSUE TITLE
Minimum Angular2 version is out of date

### ISSUE THREAD

**Issue by jasoncavaliere** [travelist/angular2-fontawesome#7]
2.0.0-rc.4 was released yesterday - I skipped on 2 and 3, but I was unable to continue using it this package because of the hard reference to 2.0.0-rc.1.   Were you planning on updating before release?  I went ahead and forked for now so that id didn't stop development, but am not looking to keep a custom copy on hand.  

Are you waiting for RTM before updating again?

**Comment by travelist** [comment]
@jasoncavaliere Thank you for the comment. Will update this package soon(maybe in a week) (I will see the 2.0.0-rc.4 later today and try to update with some changes of current code ). I've been having something to do for the last a month, this cause the slow development(and waiting for some updates on angular2), but yeah, more or less it's time to update.

Thanks again:)

**Comment by jasoncavaliere** [comment]
Awesome! I would have done the pull request  dance, but I'm prototyping something for a client and needed  a quick fix.  Is there any reason why you can't  ^2.0.0-rc.4   at this point?  I think most of the API changes are done for RTM.

**Comment by travelist** [comment]
@jasoncavaliere I've updated this package to `v0.5.0` dealing with Angular `2.2.0-rc.4`. If we hit any issues, please open a new issues or re-open this. I'd like to help:)
