### ISSUE TITLE
No directive annotation found

### ISSUE THREAD

**Issue by paralin** [travelist/angular2-fontawesome#8]
I'm getting errors in Angular2:

 Error: Uncaught (in promise): No Directive annotation found on FaDirective

Same with FaComponent

**Comment by travelist** [comment]
@paralin Thank you for opening the issue:)
I'm trying to reproduce the same error, so would you let me know which angular version are you using?
It would be helping me.

**Comment by paralin** [comment]
v2.0.0-rc4

**Comment by travelist** [comment]
I'm using `v0.5.1` and angular `2.0.0-rc4` based on https://github.com/angular/quickstart as the test environment. I couldn't get the same error so it would be helpful if I can get more information related to this issue. Thanks.

**Comment by paralin** [comment]
I'll test some more today and get back to you.

**Comment by travelist** [comment]
I closed this issue, but feel free to re-open this issue if we are hitting the same error:)

**Comment by paralin** [comment]
Okay, I'm not using the package for now but will let you know if I decide to in the future :)
